# Generated by Django 5.0.6 on 2024-06-26 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_biblestudy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblestudy',
            name='created_at',
        ),
    ]
